typography_spectrum: 0.5012736667413265
color:
  brandStrength: 0.08338515111245215
  lightness: 0.3715576301328838
  saturation: 0.09673119289800525
  rhythmicContrast: 0.06234015175141394
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.9041872282978147
name: znakovanj
navigation:
  - name: Pizzabon
    id: ad6c5669-0650-4605-adea-45e205c90713
    type: content
title: Dobrodo≈°li...Jeeeee!
